import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
function loadEnvFile(name){const p=path.join(root,name);if(!fs.existsSync(p))return;for(const raw of fs.readFileSync(p,'utf8').split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const i=line.indexOf('=');if(i<1)continue;const k=line.slice(0,i).trim();let v=line.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(process.env[k]===undefined)process.env[k]=v;}}
loadEnvFile('.env');loadEnvFile('.env.local');
const file=path.join(root,'platform-data','platform.json');
const PORT=Number(process.env.PLATFORM_PORT||3100),KEY=process.env.OLITECHS_PLATFORM_KEY||'olitech-demo-platform-key-change-me',ADMIN_USER=process.env.PLATFORM_ADMIN_USER||'platformadmin',ADMIN_PASS=process.env.PLATFORM_ADMIN_PASSWORD||'Platform@123';
const sessions=new Map();const id=()=>`pl-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const hashPassword=p=>{const salt=crypto.randomBytes(16).toString('hex');return `${salt}:${crypto.scryptSync(p,salt,64).toString('hex')}`};
const defaultPackages=[
{id:'starter',name:'Starter',tagline:'For small hotels and guest houses',price:4900,billing:'month',trialDays:7,maxRooms:30,features:['PMS reservations','Guest profiles','Check-in & check-out','Housekeeping','Basic reports']},
{id:'professional',name:'Professional',tagline:'Complete PMS & POS operations',price:8900,billing:'month',trialDays:7,maxRooms:100,features:['Everything in Starter','Restaurant POS','Kitchen KDS','Folios & room charges','Advanced revenue reports','Thermal printer routing']},
{id:'enterprise',name:'Enterprise',tagline:'For larger properties and groups',price:15900,billing:'month',trialDays:7,maxRooms:500,features:['Everything in Professional','Multi-outlet POS','Advanced permissions','Priority support','Enterprise reporting','Multi-property ready']}
];
function seed(){return {settings:{product:'OliTechs PMS & POS Licensing Platform',version:'1.1',supportWhatsApp:'+254745043121',defaultTrialDays:7},packages:defaultPackages,companies:[],auditLogs:[]}}
function load(){if(!fs.existsSync(file)){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(seed(),null,2));}const d=JSON.parse(fs.readFileSync(file,'utf8'));let changed=false;if(!Array.isArray(d.packages)||!d.packages.length){d.packages=defaultPackages;changed=true}if(!d.settings){d.settings=seed().settings;changed=true}if(!d.settings.supportWhatsApp)d.settings.supportWhatsApp='+254745043121';if(!d.settings.defaultTrialDays)d.settings.defaultTrialDays=7;if(changed)save(d);return d}
function save(d){fs.writeFileSync(file,JSON.stringify(d,null,2))}
function json(res,status,obj,extra={}){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-credentials':'true',...extra});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function platformUser(req){const sid=cookies(req).olitech_platform_session;return sid?sessions.get(sid):null}
function admin(req,res){const u=platformUser(req);if(!u){json(res,401,{error:'Platform administrator authentication required'});return null}return u}
function apiKey(req){return req.headers['x-olitechs-platform-key']===KEY}
function audit(d,action,companyId,extra={}){d.auditLogs.push({id:id(),action,companyId:companyId||null,at:new Date().toISOString(),actor:ADMIN_USER,...extra});if(d.auditLogs.length>2000)d.auditLogs=d.auditLogs.slice(-2000)}
function normalizePackage(p){return {id:p.id||`pkg-${Date.now()}`,name:String(p.name||'New package').trim(),tagline:String(p.tagline||'').trim(),price:Number(p.price||0),billing:p.billing||'month',trialDays:Number.isFinite(Number(p.trialDays))?Math.max(0,Number(p.trialDays)):7,maxRooms:Number(p.maxRooms||0),features:Array.isArray(p.features)?p.features.filter(Boolean):[],active:p.active!==false}}
async function main(req,res){const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return json(res,204,{});let b={};if(['POST','PUT','PATCH'].includes(req.method)){try{b=await body(req)}catch{return json(res,400,{error:'Invalid JSON'})}}
if(req.method==='GET'&&u.pathname==='/platform-api/health')return json(res,200,{ok:true,service:'OliTechs Licensing Platform',time:new Date().toISOString()});
if(req.method==='GET'&&u.pathname==='/platform-api/public/settings'){const d=load();return json(res,200,{supportWhatsApp:d.settings.supportWhatsApp,defaultTrialDays:d.settings.defaultTrialDays})}
if(req.method==='GET'&&u.pathname==='/platform-api/public/packages'){const d=load();return json(res,200,d.packages.filter(p=>p.active!==false))}
if(req.method==='POST'&&u.pathname==='/platform-api/login'){if(b.username!==ADMIN_USER||b.password!==ADMIN_PASS)return json(res,401,{error:'Invalid platform administrator credentials'});const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{username:ADMIN_USER,role:'platform_admin'});return json(res,200,{ok:true,user:{username:ADMIN_USER,role:'platform_admin'}},{'set-cookie':`olitech_platform_session=${sid}; HttpOnly; SameSite=Strict; Path=/`})}
if(req.method==='POST'&&u.pathname==='/platform-api/logout'){const sid=cookies(req).olitech_platform_session;if(sid)sessions.delete(sid);return json(res,200,{ok:true},{'set-cookie':'olitech_platform_session=; Max-Age=0; HttpOnly; SameSite=Strict; Path=/'})}
if(req.method==='GET'&&u.pathname==='/platform-api/session')return json(res,200,{authenticated:!!platformUser(req),user:platformUser(req)||null});
const d=load();
if(req.method==='POST'&&u.pathname==='/platform-api/register'){if(!apiKey(req))return json(res,403,{error:'Invalid platform key'});let c=d.companies.find(x=>x.installationId===b.installationId);const incomingEmail=String(b.company?.email||'').trim().toLowerCase();if(!c&&incomingEmail)c=d.companies.find(x=>String(x.company?.email||'').toLowerCase()===incomingEmail&&x.source==='public_signup');const now=new Date().toISOString();if(!c){c={id:id(),installationId:b.installationId||id(),company:b.company||{},status:'pending',subscription:{plan:'Trial',packageId:'starter',status:'pending',startsAt:null,expiresAt:null,maxRooms:0,features:[]},createdAt:now,updatedAt:now,heartbeatAt:now,provisionedAdmin:null};d.companies.push(c)}else{c.installationId=b.installationId||c.installationId;c.company={...c.company,...(b.company||{})};c.updatedAt=now;c.heartbeatAt=now}audit(d,'registration_submitted',c.id,{installationId:c.installationId});save(d);return json(res,200,{ok:true,companyId:c.id,status:c.status,subscription:c.subscription})}
if(req.method==='POST'&&u.pathname==='/platform-api/public/signup'){const email=String(b.email||'').trim().toLowerCase();const companyName=String(b.companyName||'').trim();const packageId=String(b.packageId||'');if(!companyName||!email||!packageId||!b.username)return json(res,400,{error:'Hotel name, email, package and admin username are required'});if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Enter a valid email address'});const pkg=d.packages.find(p=>p.id===packageId&&p.active!==false);if(!pkg)return json(res,400,{error:'Selected package is not available'});if(d.companies.some(c=>String(c.company?.email||'').toLowerCase()===email))return json(res,409,{error:'A company with this email is already registered'});const now=new Date();const trialDays=Math.max(0,Number(pkg.trialDays||d.settings.defaultTrialDays||7));const c={id:id(),installationId:null,company:{name:companyName,legalName:b.legalName||companyName,registrationNo:b.registrationNo||'',taxNo:b.taxNo||'',address:b.address||'',city:b.city||'',country:b.country||'Kenya',phone:b.phone||'',email,website:b.website||'',contactName:b.contactName||''},status:'pending',source:'public_signup',requestedAdmin:{username:String(b.username).trim(),name:b.contactName||b.username,email,phone:b.phone||''},subscription:{plan:pkg.name,packageId:pkg.id,status:'trial',startsAt:now.toISOString(),expiresAt:new Date(now.getTime()+trialDays*864e5).toISOString(),maxRooms:pkg.maxRooms,features:pkg.features,trialDays},createdAt:now.toISOString(),updatedAt:now.toISOString(),heartbeatAt:null,provisionedAdmin:null};d.companies.push(c);audit(d,'public_signup_submitted',c.id,{packageId:pkg.id,email});save(d);return json(res,201,{ok:true,companyId:c.id,status:c.status,package:{id:pkg.id,name:pkg.name},trialDays,trialEndsAt:c.subscription.expiresAt,message:'Your registration has been submitted. OliTechs will review and activate your hotel account.'})}
if(req.method==='GET'&&u.pathname.startsWith('/platform-api/status/')){if(!apiKey(req))return json(res,403,{error:'Invalid platform key'});const installationId=decodeURIComponent(u.pathname.split('/').pop());const c=d.companies.find(x=>x.installationId===installationId);if(!c)return json(res,404,{error:'Installation not registered'});c.heartbeatAt=new Date().toISOString();c.updatedAt=c.heartbeatAt;save(d);return json(res,200,{companyId:c.id,status:c.status,subscription:c.subscription,company:c.company,provisionedAdmin:c.provisionedAdmin?{username:c.provisionedAdmin.username,passwordHash:c.provisionedAdmin.passwordHash,role:'admin',active:true}:null})}
if(req.method==='GET'&&u.pathname==='/platform-api/admin/companies'){if(!admin(req,res))return;return json(res,200,d.companies)}
if(req.method==='GET'&&u.pathname==='/platform-api/admin/audit'){if(!admin(req,res))return;return json(res,200,d.auditLogs.slice(-500).reverse())}
if(req.method==='GET'&&u.pathname==='/platform-api/admin/packages'){if(!admin(req,res))return;return json(res,200,d.packages)}
if(req.method==='POST'&&u.pathname==='/platform-api/admin/packages'){if(!admin(req,res))return;const p=normalizePackage(b);if(d.packages.some(x=>x.id===p.id))return json(res,409,{error:'Package ID already exists'});d.packages.push(p);audit(d,'package_created',null,{packageId:p.id});save(d);return json(res,201,p)}
if(req.method==='PUT'&&u.pathname.startsWith('/platform-api/admin/packages/')){if(!admin(req,res))return;const pid=decodeURIComponent(u.pathname.split('/').pop());const i=d.packages.findIndex(x=>x.id===pid);if(i<0)return json(res,404,{error:'Package not found'});d.packages[i]=normalizePackage({...d.packages[i],...b,id:pid});audit(d,'package_updated',null,{packageId:pid});save(d);return json(res,200,d.packages[i])}
if(req.method==='DELETE'&&u.pathname.startsWith('/platform-api/admin/packages/')){if(!admin(req,res))return;const pid=decodeURIComponent(u.pathname.split('/').pop());const p=d.packages.find(x=>x.id===pid);if(!p)return json(res,404,{error:'Package not found'});d.packages=d.packages.map(x=>x.id===pid?{...x,active:false}:x);audit(d,'package_deactivated',null,{packageId:pid});save(d);return json(res,200,{ok:true})}
if(req.method==='PUT'&&u.pathname.startsWith('/platform-api/admin/companies/')){if(!admin(req,res))return;const cid=decodeURIComponent(u.pathname.split('/').pop());const c=d.companies.find(x=>x.id===cid);if(!c)return json(res,404,{error:'Company not found'});if(b.status)c.status=b.status;if(b.company)c.company={...c.company,...b.company};if(b.subscription)c.subscription={...c.subscription,...b.subscription};if(b.provisionedAdmin){const username=String(b.provisionedAdmin.username||'').trim();const password=String(b.provisionedAdmin.password||'');if(!username)return json(res,400,{error:'Hotel admin username is required'});if(password.length<8)return json(res,400,{error:'Hotel admin password must be at least 8 characters'});c.provisionedAdmin={username,name:b.provisionedAdmin.name||username,email:b.provisionedAdmin.email||c.company?.email||'',passwordHash:hashPassword(password),provisionedAt:new Date().toISOString(),active:true};}c.updatedAt=new Date().toISOString();audit(d,'company_updated',c.id,{status:c.status,packageId:c.subscription?.packageId});save(d);return json(res,200,{...c,provisionedAdmin:c.provisionedAdmin?{username:c.provisionedAdmin.username,name:c.provisionedAdmin.name,provisionedAt:c.provisionedAdmin.provisionedAt,active:c.provisionedAdmin.active}:null})}
return json(res,404,{error:'Not found'})}
http.createServer((req,res)=>main(req,res).catch(e=>{console.error(e);if(!res.headersSent)json(res,500,{error:e.message})})).listen(PORT,'0.0.0.0',()=>console.log(`OliTechs Licensing Platform http://localhost:${PORT}`));
