import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarDays,ChevronLeft,ChevronRight,Plus,Search,Users,BedDouble,Receipt,Utensils,BarChart3,Settings,RefreshCw,Database,Edit3,Trash2,Save,LayoutDashboard,LogIn,LogOut,ClipboardCheck,Wrench,Tags,Package,ShieldCheck,FileText,ChefHat,WalletCards,Menu as MenuIcon,X,UserRound,Hotel,Clock3,LockKeyhole,Building2,CreditCard,ShieldAlert,Printer,CheckCircle2,Wifi,Bluetooth,Cable,Activity,Building,ReceiptText,MessageCircle,ArrowRight,Check,PlusCircle,SaveAll,UserPlus,Layers3}from'lucide-react';
import'./styles.css';
import{PublicLanding}from'./public-site.jsx';

const A='/api';
const money=n=>`KES ${Number(n||0).toLocaleString('en-KE')}`;
const fmt=d=>d?new Date(d+'T00:00').toLocaleDateString('en-GB'):'';
const nights=(a,b)=>Math.max(1,Math.round((new Date(b)-new Date(a))/864e5));
const today='2026-09-10';

// --- Views & Views Mock Holders ---
function Head({title,sub,children}){return <div className="head"><div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{children}</div>}
function Action({label,icon:I,onClick}){return <button className="actionBtn" onClick={onClick}><I size={18}/><span>{label}</span></button>}

function EmptyState({icon:Icon,title,text:copy}){return <div className="moduleEmpty"><div className="moduleIcon"><Icon size={24}/></div><h3>{title}</h3><p>{copy}</p></div>}
function ModuleShell({title,sub,icon:Icon,stats=[],children,action}){return <section className="modulePage"><div className="moduleHead"><Head title={title} sub={sub}/>{action}</div>{stats.length>0&&<div className="moduleStats">{stats.map((s,i)=><div className="moduleStat" key={i}><span>{s.label}</span><b>{s.value}</b></div>)}</div>}{children}</section>}
function DataTable({columns,rows,empty,icon}){return rows?.length?<div className="dataTable"><div className="dataTableHead">{columns.map(c=><b key={c.key}>{c.label}</b>)}</div>{rows.map((row,i)=><div className="dataTableRow" key={row.id||i}>{columns.map(c=><span key={c.key}>{c.render?c.render(row):row[c.key]??'—'}</span>)}</div>)}</div>:<EmptyState icon={icon||Database} title={empty||'No records yet'} text="Records created in this installation will appear here automatically."/>}
function Dashboard({d,go}){const rooms=d?.rooms||[],reservations=d?.reservations||[],guests=d?.guests||[],orders=d?.orders||[];return <ModuleShell title="Dashboard" sub="Hotel operations overview" icon={LayoutDashboard} stats={[{label:'Rooms',value:rooms.length},{label:'Reservations',value:reservations.length},{label:'Guests',value:guests.length},{label:'Open orders',value:orders.filter(x=>x.status!=='settled').length}]}><div className="moduleGrid"><div className="panel"><div className="panelTitle"><h2>Today at a glance</h2><span>Live local data</span></div><div className="quickActions"><button onClick={()=>go('reservations')}><Receipt/>Reservations</button><button onClick={()=>go('checkin')}><LogIn/>Check-in / Check-out</button><button onClick={()=>go('guests')}><Users/>Guests</button><button onClick={()=>go('rooms')}><BedDouble/>Rooms</button></div></div><div className="panel"><div className="panelTitle"><h2>Recent reservations</h2><span>{reservations.length} total</span></div><DataTable icon={Receipt} columns={[{key:'id',label:'Reference'},{key:'arrival',label:'Arrival'},{key:'departure',label:'Departure'},{key:'status',label:'Status'}]} rows={reservations.slice(-5).reverse()} empty="No reservations"/></div></div></ModuleShell>}
function Planner({d,start,setStart}){const rooms=d?.rooms||[];return <ModuleShell title="Room Planner" sub="Occupancy & availability grid" icon={CalendarDays}><div className="plannerToolbar"><label>Date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><span>{rooms.length} rooms in inventory</span></div><div className="roomGrid">{rooms.map(r=><div className="roomCell" key={r.id}><b>{r.name}</b><small>{r.roomType}</small><span className="roomAvailable">Available / inventory</span></div>)}</div></ModuleShell>}
function ReservationList({d}){const rows=d?.reservations||[];return <ModuleShell title="Reservations" sub="Manage bookings" icon={Receipt} stats={[{label:'Total',value:rows.length},{label:'Confirmed',value:rows.filter(x=>x.status==='confirmed').length},{label:'Checked in',value:rows.filter(x=>x.status==='checked-in').length},{label:'Paid',value:rows.filter(x=>x.paymentStatus==='paid').length}]}><DataTable icon={Receipt} columns={[{key:'id',label:'Reference'},{key:'roomId',label:'Room'},{key:'guestId',label:'Guest'},{key:'arrival',label:'Arrival'},{key:'departure',label:'Departure'},{key:'status',label:'Status'},{key:'paymentStatus',label:'Payment'}]} rows={rows} empty="No reservations found"/></ModuleShell>}
function CheckIn({d}){const rows=(d?.reservations||[]).filter(x=>x.status==='confirmed'||x.status==='checked-in');return <ModuleShell title="Check-in / Check-out" sub="Daily arrivals & departures" icon={LogIn} stats={[{label:'Arrivals',value:rows.filter(x=>x.status==='confirmed').length},{label:'In-house',value:rows.filter(x=>x.status==='checked-in').length},{label:'Departures',value:(d?.reservations||[]).filter(x=>x.departure===new Date().toISOString().slice(0,10)).length}]}><DataTable icon={LogIn} columns={[{key:'id',label:'Reservation'},{key:'roomId',label:'Room'},{key:'arrival',label:'Arrival'},{key:'departure',label:'Departure'},{key:'status',label:'Status'}]} rows={rows} empty="No arrivals or departures"/></ModuleShell>}
function Guests({d}){const rows=d?.guests||[];return <ModuleShell title="Guests & Profiles" sub="Guest database" icon={Users} stats={[{label:'Guest profiles',value:rows.length},{label:'With email',value:rows.filter(x=>x.email).length},{label:'With phone',value:rows.filter(x=>x.phone).length}]}><DataTable icon={Users} columns={[{key:'id',label:'ID'},{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'phone',label:'Phone'},{key:'email',label:'Email'}]} rows={rows} empty="No guest profiles"/></ModuleShell>}
function Folios({d}){const rows=d?.folios||[];return <ModuleShell title="Guest Folios" sub="Billing & transactions" icon={WalletCards} stats={[{label:'Open folios',value:rows.length},{label:'Payments',value:(d?.payments||[]).length}]}><DataTable icon={WalletCards} columns={[{key:'id',label:'Folio'},{key:'guestId',label:'Guest'},{key:'status',label:'Status'},{key:'balance',label:'Balance'}]} rows={rows} empty="No folios yet"/></ModuleShell>}
function Rooms({d}){const rows=d?.rooms||[];return <ModuleShell title="Rooms & Apartments" sub="Room inventory" icon={BedDouble} stats={[{label:'Total rooms',value:rows.length},{label:'Active',value:rows.filter(x=>x.active!==false).length},{label:'Room types',value:new Set(rows.map(x=>x.roomType)).size}]}><DataTable icon={BedDouble} columns={[{key:'name',label:'Room'},{key:'roomType',label:'Type'},{key:'floor',label:'Floor'},{key:'active',label:'Status',render:r=>r.active===false?'Inactive':'Active'}]} rows={rows} empty="No rooms configured"/></ModuleShell>}
function Housekeeping({d}){const rows=d?.rooms||[];return <ModuleShell title="Housekeeping" sub="Room status & cleaning" icon={ClipboardCheck} stats={[{label:'Rooms to manage',value:rows.length},{label:'Active rooms',value:rows.filter(x=>x.active!==false).length}]}><div className="housekeepingGrid">{rows.map(r=><div className="hkCard" key={r.id}><b>{r.name}</b><span>{r.roomType}</span><strong>Ready for status update</strong></div>)}</div></ModuleShell>}
function Maintenance({d}){const rows=d?.maintenance||[];return <ModuleShell title="Maintenance" sub="Work orders" icon={Wrench} stats={[{label:'Open work orders',value:rows.filter(x=>x.status!=='closed').length},{label:'Total',value:rows.length}]}><DataTable icon={Wrench} columns={[{key:'id',label:'Work order'},{key:'title',label:'Task'},{key:'roomId',label:'Room'},{key:'status',label:'Status'}]} rows={rows} empty="No maintenance work orders"/></ModuleShell>}
function RatePlans({d}){const rows=d?.ratePlans||[];return <ModuleShell title="Rates & Availability" sub="Rate management" icon={Tags} stats={[{label:'Rate plans',value:rows.length}]}><DataTable icon={Tags} columns={[{key:'id',label:'Plan'},{key:'name',label:'Name'},{key:'price',label:'Price'},{key:'active',label:'Status',render:r=>r.active===false?'Inactive':'Active'}]} rows={rows} empty="No rate plans configured"/></ModuleShell>}
function POS({d}){const rows=d?.orders||[];return <ModuleShell title="Restaurant POS" sub="Point of Sale" icon={Utensils} stats={[{label:'Orders',value:rows.length},{label:'Open',value:rows.filter(x=>x.status!=='settled').length},{label:'Menu items',value:(d?.menu||[]).length}]}><DataTable icon={Utensils} columns={[{key:'id',label:'Order'},{key:'tableId',label:'Table'},{key:'status',label:'Status'},{key:'total',label:'Total'}]} rows={rows} empty="No POS orders"/></ModuleShell>}
function Kitchen({d}){const rows=(d?.orders||[]).filter(x=>x.status!=='settled');return <ModuleShell title="Kitchen / KDS" sub="Kitchen Display System" icon={ChefHat} stats={[{label:'Open tickets',value:rows.length}]}><DataTable icon={ChefHat} columns={[{key:'id',label:'Ticket'},{key:'tableId',label:'Table'},{key:'status',label:'Status'}]} rows={rows} empty="Kitchen queue is clear"/></ModuleShell>}
function MenuPage({d}){const rows=d?.menu||[];return <ModuleShell title="Menu & Products" sub="POS Menu items" icon={Package} stats={[{label:'Menu items',value:rows.length},{label:'Categories',value:new Set(rows.map(x=>x.category)).size}]}><DataTable icon={Package} columns={[{key:'name',label:'Item'},{key:'category',label:'Category'},{key:'price',label:'Price'}]} rows={rows} empty="No menu items configured"/></ModuleShell>}
function Reports({d}){const reservations=d?.reservations||[],orders=d?.orders||[];const revenue=reservations.reduce((n,r)=>n+Number(r.rate||0),0)+orders.reduce((n,r)=>n+Number(r.total||0),0);return <ModuleShell title="Statistics & Revenue" sub="Reports and analytics" icon={BarChart3} stats={[{label:'Reservations',value:reservations.length},{label:'POS orders',value:orders.length},{label:'Recorded revenue',value:'KES '+revenue.toLocaleString()}]}><div className="reportGrid"><div className="panel"><h2>Reservation status</h2>{['confirmed','checked-in','cancelled'].map(s=><div className="reportLine" key={s}><span>{s}</span><b>{reservations.filter(r=>r.status===s).length}</b></div>)}</div><div className="panel"><h2>Payment status</h2>{['paid','partial','unpaid'].map(s=><div className="reportLine" key={s}><span>{s}</span><b>{reservations.filter(r=>r.paymentStatus===s).length}</b></div>)}</div></div></ModuleShell>}
function NightAudit({d}){const reservations=d?.reservations||[];return <ModuleShell title="Night Audit" sub="End of day processing" icon={Clock3} stats={[{label:'Reservations',value:reservations.length},{label:'Paid',value:reservations.filter(x=>x.paymentStatus==='paid').length},{label:'Unpaid',value:reservations.filter(x=>x.paymentStatus==='unpaid').length}]}><div className="panel auditReady"><Clock3/><h2>Night audit workspace</h2><p>Review arrivals, departures, payments and operational totals before closing the business day.</p><div className="auditChecklist"><span>✓ Review arrivals and departures</span><span>✓ Review payment status</span><span>✓ Review room inventory</span><span>• Final close requires authorized action</span></div></div></ModuleShell>}
function UsersPage({d}){const rows=d?.staff||d?.users||[];return <ModuleShell title="Users & Permissions" sub="Staff access and roles" icon={ShieldCheck} stats={[{label:'Accounts',value:rows.length},{label:'Active',value:rows.filter(x=>x.active!==false).length}]}><DataTable icon={ShieldCheck} columns={[{key:'name',label:'Name'},{key:'username',label:'Username'},{key:'role',label:'Role'},{key:'active',label:'Status',render:r=>r.active===false?'Inactive':'Active'}]} rows={rows} empty="No staff accounts"/></ModuleShell>}
function SettingsPage({health}){return <ModuleShell title="Configuration" sub="Hotel operational settings" icon={Settings}><div className="settingsGrid"><div className="panel"><h2>System</h2><p>Database: <b>{health?.mode||'Local'}</b></p><p>Connection status: <b>Connected</b></p></div><div className="panel"><h2>Hotel settings</h2><p>Operational configuration is controlled by your licensed hotel installation.</p><p>Platform subscription controls are managed separately by OliTechs Platform Admin.</p></div></div></ModuleShell>}
function ReservationModal({r,d,close,refresh,toast}){return <div className="modal"><div className="modalHead"><h2>Reservation</h2><button onClick={close}><X/></button></div><div className="modalBody"><p>Reservation <b>{r?.id||'New'}</b></p><p>Selecting a reservation opens its operational context here. Guest, room, dates and payment information are available from the Reservations workspace.</p><button className="primary" onClick={close}>Close</button></div></div>}

function Login({onLogin}){
 const saved=()=>{try{return localStorage.getItem('olitech_login_username')||'Admin'}catch{return'Admin'}};
 const[f,setF]=useState({username:saved(),password:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[remember,setRemember]=useState(true),[help,setHelp]=useState(false),[other,setOther]=useState(false);
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setErr('');try{const r=await fetch(A+'/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const x=await r.json();if(!r.ok)throw Error(x.error||'Invalid username or password');if(remember){try{localStorage.setItem('olitech_login_username',f.username)}catch{}}else{try{localStorage.removeItem('olitech_login_username')}catch{}}onLogin(x)}catch(e){setErr(e.message||'Invalid username or password')}finally{setBusy(false)}};
 return <div className="loginScreen">
  <div className="loginGlow loginGlowOne"/><div className="loginGlow loginGlowTwo"/>
  <div className="loginCard loginCardPro">
   <section className="loginWelcome" aria-label="OliTechs welcome">
    <div className="loginPattern"/><div className="loginOrb orbOne"/><div className="loginOrb orbTwo"/><div className="loginBlock blockOne"/><div className="loginBlock blockTwo"/>
    <div className="welcomeContent">
     <div className="welcomeLogo"><img src="/olitechs-logo.svg" alt="OliTechs PMS & POS"/></div>
     <span className="welcomeEyebrow">HOTEL OPERATIONS PLATFORM</span>
     <h2>WELCOME</h2>
     <h3>Run your hotel<br/>with confidence.</h3>
     <p>One secure workspace for front office, rooms, housekeeping, restaurant POS, payments and daily hotel operations.</p>
     <div className="welcomeFeatures"><span><CheckCircle2 size={15}/> Local-first & secure</span><span><Activity size={15}/> Live operations</span><span><ShieldCheck size={15}/> Role-based access</span></div>
    </div>
    <div className="welcomeFooter"><span>OLITECHS SYSTEMS</span><span>v2.1</span></div>
   </section>
   <section className="loginFormPanel">
    <div className="loginTopbar"><span className="statusPill"><span/> System online</span><span className="loginLocale">{navigator.language?.toUpperCase()||'EN'}</span></div>
    <div className="loginIntro"><div className="mobileBrand"><img src="/olitechs-mark.svg" alt="OliTechs"/></div><span className="loginKicker">SECURE ACCESS</span><h1>Sign in</h1><p>Access your hotel operations dashboard.</p></div>
    <form onSubmit={submit} noValidate>
     <label className="loginField"><span className="fieldIcon"><UserRound size={18}/></span><span className="fieldLabel">User Name</span><input aria-label="User Name" autoComplete="username" autoFocus value={f.username} onChange={e=>setF({...f,username:e.target.value})} placeholder="Enter your username"/></label>
     <label className="loginField"><span className="fieldIcon"><LockKeyhole size={18}/></span><span className="fieldLabel">Password</span><input aria-label="Password" autoComplete="current-password" type={show?'text':'password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="Enter your password"/><button type="button" className="showPassword" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?'HIDE':'SHOW'}</button></label>
     {err&&<div className="loginError" role="alert"><ShieldAlert size={17}/><div><b>Sign-in failed</b><span>{err}</span></div></div>}
     <div className="loginControls"><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span className="checkmark"><Check size={13}/></span><span>Remember me</span></label><button type="button" className="textLink" onClick={()=>{setHelp(!help);setOther(false)}}>Forgot Password?</button></div>
     {help&&<div className="loginHelper"><b>Need access?</b><span>This is a local hotel installation. Password recovery is handled by an authorized OliTechs administrator; no password is sent by this screen.</span></div>}
     <button className="primary loginSubmit" disabled={busy}>{busy?<><span className="spinner"/>Signing in…</>:<>Sign in securely <ArrowRight size={17}/></>}</button>
    </form>
    <div className="loginDivider"><span>Or</span></div>
    <button type="button" className="otherSignIn" onClick={()=>{setOther(!other);setHelp(false)}}><Layers3 size={17}/><span>Sign in with other</span><ChevronRight size={16}/></button>
    {other&&<div className="loginHelper otherHelper"><b>Alternative access</b><span>Additional sign-in providers can be enabled by your hotel administrator. Local username and password remain available.</span></div>}
    <div className="loginSignup">Don't have an account? <button type="button" onClick={()=>{window.location.href='/signup'}}>Sign Up</button></div>
    <div className="securityNote proSecurity"><LockKeyhole size={13}/><span>Your session is protected with secure local authentication.</span><span className="securityDot"/></div>
   </section>
  </div>
 </div>
}

export function App(){
 const[d,setD]=useState(null),[health,setH]=useState(null),[session,setSession]=useState(null),[page,setP]=useState('dashboard'),[modal,setM]=useState(null),[toast,setT]=useState(''),[side,setSide]=useState(true),[start,setStart]=useState(new Date().toISOString().slice(0,10));
 const load=async()=>{
  try{
   const sr=await fetch(A+'/session');
   const ss=await sr.json();
   setSession(ss);
   setH(await fetch(A+'/health').then(r=>r.json()).catch(()=>({mode:'local'})));
   if(ss.authenticated){
    const br=await fetch(A+'/bootstrap');
    if(br.ok)setD(await br.json());
   }
  }catch(e){
   setSession({authenticated:false});
  }
 };
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setT(''),2500);return()=>clearTimeout(t)}},[toast]);

 if(!session)return <div className="loading">Loading secure OliTechs…</div>;
 if(!session.authenticated)return <Login onLogin={load}/>;
 const isAdmin=session.user?.role==='admin';const expired=!session.subscriptionActive;const needsCompanySetup=isAdmin&&(!session.company?.name||session.company?.name==='OliTechs Demo Hotel');
 if(expired&&!isAdmin)return <Paywall subscription={session.subscription} onLogout={async()=>{await fetch(A+'/logout',{method:'POST'});setSession({authenticated:false})}}/>;
 if(needsCompanySetup)return <CompanySetup company={session.company||{}} onDone={load}/>;
 if(!d&&page!=='admin')return <div className="loading">Loading OliTechs PMS & POS…</div>;
 const licensedFeatures=session.subscription?.features;const hasFeature=f=>!Array.isArray(licensedFeatures)||licensedFeatures.length===0||licensedFeatures.includes(f);const groups=[{title:'Front Office',items:[['dashboard','Dashboard',LayoutDashboard],['planner','Room Planner',CalendarDays,'pms'],['reservations','Reservations',Receipt,'reservations'],['checkin','Check-in / Check-out',LogIn,'frontdesk'],['guests','Guests & Profiles',Users,'guests'],['folios','Guest Folios',WalletCards,'folios']]},{title:'Hotel Operations',items:[['rooms','Rooms & Apartments',BedDouble,'pms'],['housekeeping','Housekeeping',ClipboardCheck,'housekeeping'],['maintenance','Maintenance',Wrench,'maintenance'],['rateplans','Rates & Availability',Tags,'rateplans']]},{title:'Food & Beverage',items:[['pos','Restaurant POS',Utensils,'pos'],['kitchen','Kitchen / KDS',ChefHat,'kds'],['menu','Menu & Products',Package,'menu']]},{title:'Management',items:[['reports','Statistics & Revenue',BarChart3,'reports_basic'],['nightaudit','Night Audit',Clock3,'night_audit'],['users','Users & Permissions',ShieldCheck,'multi_user'],['settings','Configuration',Settings,'advanced_admin']]}].map(g=>({...g,items:g.items.filter(x=>!x[3]||hasFeature(x[3]))})).filter(g=>g.items.length);
 const logout=async()=>{await fetch(A+'/logout',{method:'POST'});setSession({authenticated:false});setD(null)};
 return <div className="app"><header><button className="icon" onClick={()=>setSide(!side)}>{side?<X/>:<MenuIcon/>}</button><div className="brandLogoWrap"><img className="brandLogo" src="/olitechs-logo.svg" alt="OliTechs PMS & POS"/></div><div className="top"><span className="live">● {health?.mode==='postgresql-configured-json-adapter'?'PostgreSQL':'Local database'}</span>{session.subscription&&<span className={'subPill '+(session.subscriptionActive?'active':'expired')}>{session.subscription.plan} · {session.subscriptionActive?'Active':'Expired'}</span>}<button className="icon" onClick={load}><RefreshCw size={17}/></button><span className="email">{session.user?.name||'User'}</span><button className="icon" title="Lock / sign out" onClick={logout}><LockKeyhole size={17}/></button></div></header><div className="body">{side&&<aside>{groups.map(g=><div className="navGroup" key={g.title}><div className="navTitle">{g.title}</div>{g.items.map(([id,label,I])=><button className={page===id?'sel':''} key={id} onClick={()=>setP(id)}><I size={16}/><span>{label}</span></button>)}</div>)}<div className="asideBottom"><div><Database size={16}/><span>Database<br/><small>{health?.mode==='postgresql-configured-json-adapter'?'PostgreSQL server':'Local persistent DB'}</small></span></div><button onClick={async()=>{if(!isAdmin)return;await fetch(A+'/reset-demo',{method:'POST'});await load();setT('Demo data reset')}}><RefreshCw size={14}/>Reset demo data</button></div></aside>}<main>{page==='dashboard'&&<Dashboard d={d} go={setP}/>} {page==='planner'&&<Planner d={d} start={start} setStart={setStart} open={setM}/>} {page==='reservations'&&<ReservationList d={d} open={setM}/>} {page==='checkin'&&<CheckIn d={d} refresh={load} toast={setT}/>} {page==='guests'&&<Guests d={d}/>} {page==='folios'&&<Folios d={d}/>} {page==='rooms'&&<Rooms d={d} refresh={load}/>} {page==='housekeeping'&&<Housekeeping d={d} refresh={load}/>} {page==='maintenance'&&<Maintenance d={d} refresh={load}/>} {page==='rateplans'&&<RatePlans d={d}/>} {page==='pos'&&<POS d={d} refresh={load} toast={setT}/>} {page==='kitchen'&&<Kitchen d={d}/>} {page==='menu'&&<MenuPage d={d}/>} {page==='reports'&&<Reports d={d}/>} {page==='nightaudit'&&<NightAudit d={d} refresh={load} toast={setT}/>} {page==='users'&&<UsersPage d={d}/>} {page==='settings'&&<SettingsPage health={health}/>}  </main></div>{modal&&<ReservationModal r={modal} d={d} close={()=>setM(null)} refresh={load} toast={setT}/>} {toast&&<div className="toast">{toast}</div>}</div>
}

function CompanySetup({company,onDone}){const[f,setF]=useState({...company,name:'',legalName:'',address:'',city:'',country:'Kenya',phone:'',email:'',website:'',currency:'KES',taxNo:'',receiptHeader:'',receiptFooter:'Thank you for choosing us.',taxLabel:'VAT',taxRate:0,invoicePrefix:'INV',receiptPrefix:'RCP',paperWidth:42});const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const save=async e=>{e.preventDefault();if(!String(f.name||'').trim()){setErr('Business / hotel name is required');return}setBusy(true);setErr('');try{const r=await fetch(A+'/admin/company',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const x=await r.json();if(!r.ok)throw Error(x.error||'Could not save company details');onDone()}catch(e){setErr(e.message)}finally{setBusy(false)}};return <div className="loginScreen"><div className="modal setupWizard"><div className="modalHead"><div><h2>Set up your company</h2><p className="muted">Enter the details that will appear on invoices, bills and thermal receipts.</p></div></div><form className="form adminForm" onSubmit={save}>{[['name','Business / hotel name'],['legalName','Legal company name'],['taxNo','Tax / PIN number'],['address','Address'],['city','City'],['country','Country'],['phone','Phone'],['email','Email'],['website','Website'],['currency','Currency'],['receiptHeader','Receipt / bill header'],['receiptFooter','Receipt / bill footer'],['taxLabel','Tax label'],['taxRate','Tax rate (%)'],['invoicePrefix','Invoice / bill prefix'],['receiptPrefix','Receipt prefix'],['paperWidth','Thermal paper width']].map(([k,l])=><label key={k}>{l}<input required={k==='name'} type={['taxRate','paperWidth'].includes(k)?'number':'text'} value={f[k]??''} onChange={e=>setF({...f,[k]:['taxRate','paperWidth'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</form>{err&&<div className="error">{err}</div>}<div className="foot"><span className="muted">You can change these details later in Administration.</span><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save company & continue'}</button></div></div></div>}
function Paywall({subscription,onLogout}){return <div className="loginScreen"><div className="loginCard paywall"><div className="shield warning"><ShieldAlert size={38}/></div><h1>Subscription required</h1><p>The hotel subscription is not currently active.</p><div className="subscriptionBox"><b>{subscription?.plan||'Plan'}</b><span>Status: {subscription?.status||'expired'}</span><span>Expiry: {subscription?.expiresAt?new Date(subscription.expiresAt).toLocaleString('en-GB'):'Not set'}</span></div><p className="muted">Please contact your OliTechs administrator to renew the hotel subscription.</p><button onClick={onLogout}>Sign out</button></div></div>}

function AdminCentre({session,onUpdated,toast}){
 const[c,setC]=useState(session.company||{}),[sub,setSub]=useState(session.subscription||{}),[tab,setTab]=useState('overview'),[app,setApp]=useState(session.companyApplication||{}),[printers,setPrinters]=useState([]),[platform,setPlatform]=useState(null),[msg,setMsg]=useState('');
 const loadAdmin=async()=>{try{const [a,p,pi]=await Promise.all([fetch(A+'/admin/company-application'),fetch(A+'/admin/printers'),fetch(A+'/admin/platform-info')]);if(a.ok)setApp(await a.json());if(p.ok)setPrinters(await p.json());if(pi.ok)setPlatform(await pi.json())}catch(e){}};useEffect(()=>{loadAdmin()},[]);
 const saveCompany=async()=>{const r=await fetch(A+'/admin/company',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(c)});const x=await r.json();if(r.ok){setC(x);setMsg('Company details saved to this local machine');toast('Company details saved');onUpdated()}else setMsg(x.error||'Unable to save')};
 const review=async(status)=>{const r=await fetch(A+'/admin/company-application',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({status,company:c,notes:app.notes||''})});const x=await r.json();if(r.ok){setApp(x);toast(`Company registration ${status}`);onUpdated()}else setMsg(x.error||'Unable to update registration')};
 const saveSub=async()=>{const r=await fetch(A+'/admin/subscription',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(sub)});const x=await r.json();if(r.ok){setSub(x);toast('Subscription updated');onUpdated()}else setMsg(x.error||'Unable to save')};
 const addPrinter=async()=>{const pr={name:'New Thermal Printer',type:'network',ip:'',port:9100,printerName:'',department:'reception',documents:['order','bill','receipt'],enabled:true};const r=await fetch(A+'/admin/printers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(pr)});if(r.ok){setPrinters([...printers,await r.json()]);toast('Printer added')}};
 const updatePrinter=async(pr)=>{const r=await fetch(A+'/admin/printers/'+pr.id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(pr)});if(r.ok){const saved=await r.json();setPrinters(printers.map(x=>x.id===pr.id?saved:x));toast('Printer saved')}};
 const samplePrint=async(type)=>{const pr=printers.find(x=>(x.documents||[]).includes(type)&&x.enabled!==false)||printers[0];if(!pr)return toast('Configure a thermal printer first');const r=await fetch(A+'/admin/print-document',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({printerId:pr.id,documentType:type,reference:'SAMPLE-001',customer:c.name||'Guest',items:[{name:type==='bill'?'Accommodation / Services':'Thermal printer test',qty:1,price:100}],subtotal:100,tax:100*(Number(c.taxRate||0)/100),total:100+(100*(Number(c.taxRate||0)/100)),paymentMethod:'Sample'})});const x=await r.json();toast(r.ok?type.toUpperCase()+' sample printed':x.error||'Print failed')};
 const testPrinter=async(pr)=>{const r=await fetch(A+'/admin/printers/'+pr.id+'/test',{method:'POST'});const x=await r.json();toast(r.ok?'Test print sent':x.error||'Test print failed')};
 const removePrinter=async(pr)=>{if(!confirm(`Remove ${pr.name}?`))return;await fetch(A+'/admin/printers/'+pr.id,{method:'DELETE'});setPrinters(printers.filter(x=>x.id!==pr.id));toast('Printer removed')};\n const platformRegister=async()=>{const r=await fetch(A+'/admin/platform/register',{method:'POST'});const x=await r.json();if(r.ok){toast('Hotel submitted to OliTechs Platform');loadAdmin();onUpdated()}else toast(x.error||'Platform registration failed')};\n const platformSync=async()=>{const r=await fetch(A+'/admin/platform/sync',{method:'POST'});const x=await r.json();if(r.ok){toast('Package and subscription synced from Platform Admin');onUpdated();loadAdmin()}else toast(x.error||'Platform sync failed')};
 const pending=app.status==='pending'||app.status==='submitted'; const activeSub=sub.status==='active'&&(!sub.expiresAt||new Date(sub.expiresAt)>new Date());
 return <section><Head title="Administrator Dashboard" sub="Protected platform administration, company approval, subscriptions and printing"><span className="adminShield"><ShieldCheck size={16}/> Administrator only</span></Head>
 <div className="adminTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Activity size={16}/>Overview</button><button className={tab==='registration'?'active':''} onClick={()=>setTab('registration')}><Building2 size={16}/>Company registration</button><button className={tab==='printers'?'active':''} onClick={()=>setTab('printers')}><Printer size={16}/>Thermal printers</button><button className={tab==='subscription'?'active':''} onClick={()=>setTab('subscription')}><CreditCard size={16}/>Subscription & Paywall</button></div>
 {tab==='overview'&&<><div className="adminStats"><div className="adminMetric"><Activity/><b>{app.status||'pending'}</b><span>Registration status</span></div><div className="adminMetric"><CreditCard/><b>{sub.plan||'Trial'}</b><span>{activeSub?'Subscription active':'Subscription blocked'}</span></div><div className="adminMetric"><Printer/><b>{printers.length}</b><span>Configured printers</span></div><div className="adminMetric"><ShieldCheck/><b>{dStatus(app.status)}</b><span>System access</span></div></div><div className="dashboardGrid"><div className="panel"><h2>Administrator actions</h2><Action label="Review company registration" icon={Building2} onClick={()=>setTab('registration')}/><Action label="Configure thermal printers" icon={Printer} onClick={()=>setTab('printers')}/><Action label="Manage subscription and paywall" icon={CreditCard} onClick={()=>setTab('subscription')}/></div><div className="panel"><h2>Central licensing</h2><p className="muted">This hotel installation can register with the separate OliTechs Platform Admin. Once a package is assigned centrally, sync applies the package, features, room limit and subscription status locally.</p><div className="subscriptionBox"><span>Platform: <b>{platform?.platformConfigured?'Configured':'Using local development endpoint'}</b></span><span>Central status: <b>{app.status||'pending'}</b></span><span>Last sync: <b>{app.lastSyncedAt?new Date(app.lastSyncedAt).toLocaleString('en-GB'):'Never'}</b></span></div><div className="foot"><button onClick={platformRegister}>Register / submit hotel</button><button className="primary" onClick={platformSync}>Sync package & subscription</button></div></div></div></>}
 {tab==='registration'&&<div className="panel adminPanel"><h2>Company registration and approval</h2><p className="muted">Register the hotel on this local machine, review the submitted details, and explicitly approve or reject access to OliTechs.</p><div className="registrationStatus"><span className={'statusDot '+(app.status==='approved'?'ok':pending?'pending':'blocked')}></span><b>{String(app.status||'pending').toUpperCase()}</b><span>{app.reviewedAt?`Reviewed ${new Date(app.reviewedAt).toLocaleString('en-GB')}`:'Awaiting administrator review'}</span></div><div className="form adminForm">{[['name','Trading / hotel name'],['legalName','Legal company name'],['registrationNo','Company registration number'],['taxNo','Tax / PIN number'],['address','Address'],['city','City'],['country','Country'],['phone','Phone'],['email','Email'],['website','Website'],['currency','Currency'],['timezone','Timezone'],['receiptHeader','Receipt / bill header'],['receiptFooter','Receipt / bill footer'],['taxLabel','Tax label'],['taxRate','Tax rate (%)'],['invoicePrefix','Invoice / bill prefix'],['receiptPrefix','Receipt prefix'],['paperWidth','Thermal paper width (characters)']].map(([k,l])=><label key={k}>{l}<input type={['taxRate','paperWidth'].includes(k)?'number':'text'} value={c[k]??''} onChange={e=>setC({...c,[k]:['taxRate','paperWidth'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</div><label className="full adminNote">Administrator review notes<textarea value={app.notes||''} onChange={e=>setApp({...app,notes:e.target.value})}/></label><div className="foot"><span>{msg}</span><button onClick={saveCompany}><Save size={15}/>Save locally</button><button className="danger" onClick={()=>review('rejected')}>Reject</button><button className="primary" onClick={()=>review('approved')}><CheckCircle2 size={15}/>Approve company</button></div></div>}
 {tab==='printers'&&<div><div className="printerIntro panel"><div><h2>Thermal printer configuration</h2><p className="muted">Route orders, bills and receipts to reception, kitchen, bar or another outlet. Network printers can print directly by IP and port. Bluetooth and USB/wired printers use the Windows printer queue.</p></div><button className="primary" onClick={addPrinter}><Plus size={15}/>Add printer</button></div><div className="printerGrid">{printers.map(pr=><PrinterCard key={pr.id} pr={pr} update={updatePrinter} test={testPrinter} remove={removePrinter}/>)}</div>{!printers.length&&<div className="empty">No thermal printers configured.</div>}<div className="panel printSamples"><h2>Branded receipt & bill preview</h2><p className="muted">The saved company details are automatically placed in the header/footer of thermal receipts and bills.</p><div className="printerActions"><button onClick={()=>samplePrint('receipt')}><ReceiptText size={14}/>Print sample receipt</button><button onClick={()=>samplePrint('bill')}><FileText size={14}/>Print sample bill</button></div></div></div>}
 {tab==='subscription'&&<div className="panel adminPanel"><h2>Subscription & Paywall</h2><p className="muted">Monitor the hotel subscription from the administrator dashboard. Expired, suspended or past-due subscriptions block normal hotel users while keeping administrator access available.</p><div className="subscriptionBox"><b>{sub.plan||'Plan'}</b><span>Status: {sub.status||'active'}</span><span>Expires: {sub.expiresAt?new Date(sub.expiresAt).toLocaleString('en-GB'):'not configured'}</span><span>Room limit: {sub.maxRooms||'Unlimited'}</span><span>{sub.expiresAt&&new Date(sub.expiresAt)>new Date()?Math.ceil((new Date(sub.expiresAt)-new Date())/864e5)+' days remaining':'Subscription expired'}</span></div><div className="form adminForm">{[['plan','Plan name'],['status','Status'],['startsAt','Start date/time'],['expiresAt','Expiry date/time'],['maxRooms','Maximum rooms']].map(([k,l])=><label key={k}>{l}{k==='status'?<select value={sub[k]||'active'} onChange={e=>setSub({...sub,[k]:e.target.value})}><option value="active">Active</option><option value="past_due">Past due</option><option value="expired">Expired</option><option value="suspended">Suspended</option></select>:<input type={k==='maxRooms'?'number':k.endsWith('At')?'datetime-local':'text'} value={k.endsWith('At')&&sub[k]?String(sub[k]).slice(0,16):sub[k]||''} onChange={e=>setSub({...sub,[k]:k==='maxRooms'?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="foot"><span/><button className="primary" onClick={saveSub}><Save size={15}/>Save subscription</button></div></div>}
 </section>}

function dStatus(status){return status==='approved'?'Enabled':status==='pending'||status==='submitted'?'Pending':'Blocked'}

function PrinterCard({pr,update,test,remove}){const[local,setLocal]=useState(pr);useEffect(()=>setLocal(pr),[pr]);const set=(k,v)=>setLocal({...local,[k]:v});return <div className="panel printerCard"><div className="printerHead"><div><Printer/><h3>{pr.name||'Thermal printer'}</h3><small>{pr.department||'reception'} · {pr.type||'network'}</small></div><label className="switch"><input type="checkbox" checked={local.enabled!==false} onChange={e=>set('enabled',e.target.checked)}/><span>Enabled</span></label></div><div className="printerForm"><label>Printer name<input value={local.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Connection<select value={local.type||'network'} onChange={e=>set('type',e.target.value)}><option value="network">Network / IP</option><option value="bluetooth">Bluetooth</option><option value="usb">USB / Wired</option></select></label><label>Outlet / destination<select value={local.department||'reception'} onChange={e=>set('department',e.target.value)}><option value="reception">Reception</option><option value="kitchen">Kitchen</option><option value="bar">Bar</option><option value="restaurant">Restaurant</option><option value="other">Other</option></select></label>{pr.type==='network'?<><label>IP address<input placeholder="192.168.1.100" value={local.ip||''} onChange={e=>set('ip',e.target.value)}/></label><label>Port<input type="number" value={local.port||9100} onChange={e=>set('port',Number(e.target.value))}/></label></>:<label>Windows printer name<input placeholder="Exact Windows printer queue name" value={local.printerName||''} onChange={e=>set('printerName',e.target.value)}/></label>}<label className="full">Print documents<select multiple value={local.documents||[]} onChange={e=>set('documents',[...e.target.selectedOptions].map(x=>x.value))}><option value="order">Orders</option><option value="bill">Bills</option><option value="receipt">Receipts</option></select></label></div><div className="printerActions"><button onClick={()=>test(local)}><ReceiptText size={14}/>Test print</button><button className="primary" onClick={()=>update(local)}><Save size={14}/>Save</button><button className="danger" onClick={()=>remove(pr)}><Trash2 size={14}/>Remove</button></div></div>}

export default App;
