import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarDays,ChevronLeft,ChevronRight,Plus,Search,Users,BedDouble,Receipt,Utensils,BarChart3,Settings,RefreshCw,Database,Edit3,Trash2,Save,LayoutDashboard,LogIn,LogOut,ClipboardCheck,Wrench,Tags,Package,ShieldCheck,FileText,ChefHat,WalletCards,Menu as MenuIcon,X,UserRound,Hotel,Clock3,LockKeyhole,Building2,CreditCard,ShieldAlert,Printer,CheckCircle2,Wifi,Bluetooth,Cable,Activity,Building,ReceiptText,MessageCircle,ArrowRight,Check,PlusCircle,SaveAll,UserPlus,Layers3}from'lucide-react';
import'./styles.css';
import{PublicLanding}from'./public-site.jsx';

const A='/api';
const money=n=>`KES ${Number(n||0).toLocaleString('en-KE')}`;
const fmt=d=>d?new Date(d+'T00:00').toLocaleDateString('en-GB'):'';
const nights=(a,b)=>Math.max(1,Math.round((new Date(b)-new Date(a))/864e5));
const today='2026-09-10';

// --- Views & Views Mock Holders ---
function Head({title,sub,children}){return <div className="head"><div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{children}</div>}
function Action({label,icon:I,onClick}){return <button className="actionBtn" onClick={onClick}><I size={18}/><span>{label}</span></button>}

function Dashboard({d,go}){return <section><Head title="Dashboard" sub="Hotel operations overview"/></section>}
function Planner({d,start,setStart,open}){return <section><Head title="Room Planner" sub="Occupancy & availability grid"/></section>}
function ReservationList({d,open}){return <section><Head title="Reservations" sub="Manage bookings"/></section>}
function CheckIn({d,refresh,toast}){return <section><Head title="Check-in / Check-out" sub="Daily arrivals & departures"/></section>}
function Guests({d}){return <section><Head title="Guests & Profiles" sub="Guest database"/></section>}
function Folios({d}){return <section><Head title="Guest Folios" sub="Billing & transactions"/></section>}
function Rooms({d,refresh}){return <section><Head title="Rooms & Apartments" sub="Room inventory"/></section>}
function Housekeeping({d,refresh}){return <section><Head title="Housekeeping" sub="Room status & cleaning"/></section>}
function Maintenance({d,refresh}){return <section><Head title="Maintenance" sub="Work orders"/></section>}
function RatePlans({d}){return <section><Head title="Rates & Availability" sub="Rate management"/></section>}
function POS({d,refresh,toast}){return <section><Head title="Restaurant POS" sub="Point of Sale"/></section>}
function Kitchen({d}){return <section><Head title="Kitchen / KDS" sub="Kitchen Display System"/></section>}
function MenuPage({d}){return <section><Head title="Menu & Products" sub="POS Menu items"/></section>}
function Reports({d}){return <section><Head title="Statistics & Revenue" sub="Reports and analytics"/></section>}
function NightAudit({d,refresh,toast}){return <section><Head title="Night Audit" sub="End of day processing"/></section>}
function UsersPage({d}){return <section><Head title="Users & Permissions" sub="User management"/></section>}
function SettingsPage({health}){return <section><Head title="Configuration" sub="System settings"/></section>}
function ReservationModal({r,d,close,refresh,toast}){return <div className="modal"><div className="modalHead"><h2>Reservation</h2><button onClick={close}><X/></button></div></div>}

function Login({onLogin}){
 const saved=()=>{try{return localStorage.getItem('olitech_login_username')||'Admin'}catch{return'Admin'}};
 const[f,setF]=useState({username:saved(),password:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[remember,setRemember]=useState(true),[help,setHelp]=useState(false),[other,setOther]=useState(false);
 const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setErr('');try{const r=await fetch(A+'/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const x=await r.json();if(!r.ok)throw Error(x.error||'Invalid username or password');if(remember){try{localStorage.setItem('olitech_login_username',f.username)}catch{}}else{try{localStorage.removeItem('olitech_login_username')}catch{}}onLogin(x)}catch(e){setErr(e.message||'Invalid username or password')}finally{setBusy(false)}};
 return <div className="loginScreen">
  <div className="loginGlow loginGlowOne"/><div className="loginGlow loginGlowTwo"/>
  <div className="loginCard loginCardPro">
   <section className="loginWelcome" aria-label="OliTechs welcome">
    <div className="loginPattern"/><div className="loginOrb orbOne"/><div className="loginOrb orbTwo"/><div className="loginBlock blockOne"/><div className="loginBlock blockTwo"/>
    <div className="welcomeContent">
     <div className="welcomeLogo"><img src="/olitechs-logo.svg" alt="OliTechs PMS & POS"/></div>
     <span className="welcomeEyebrow">HOTEL OPERATIONS PLATFORM</span>
     <h2>WELCOME</h2>
     <h3>Run your hotel<br/>with confidence.</h3>
     <p>One secure workspace for front office, rooms, housekeeping, restaurant POS, payments and daily hotel operations.</p>
     <div className="welcomeFeatures"><span><CheckCircle2 size={15}/> Local-first & secure</span><span><Activity size={15}/> Live operations</span><span><ShieldCheck size={15}/> Role-based access</span></div>
    </div>
    <div className="welcomeFooter"><span>OLITECHS SYSTEMS</span><span>v2.1</span></div>
   </section>
   <section className="loginFormPanel">
    <div className="loginTopbar"><span className="statusPill"><span/> System online</span><span className="loginLocale">{navigator.language?.toUpperCase()||'EN'}</span></div>
    <div className="loginIntro"><div className="mobileBrand"><img src="/olitechs-mark.svg" alt="OliTechs"/></div><span className="loginKicker">SECURE ACCESS</span><h1>Sign in</h1><p>Access your hotel operations dashboard.</p></div>
    <form onSubmit={submit} noValidate>
     <label className="loginField"><span className="fieldIcon"><UserRound size={18}/></span><span className="fieldLabel">User Name</span><input aria-label="User Name" autoComplete="username" autoFocus value={f.username} onChange={e=>setF({...f,username:e.target.value})} placeholder="Enter your username"/></label>
     <label className="loginField"><span className="fieldIcon"><LockKeyhole size={18}/></span><span className="fieldLabel">Password</span><input aria-label="Password" autoComplete="current-password" type={show?'text':'password'} value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="Enter your password"/><button type="button" className="showPassword" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?'HIDE':'SHOW'}</button></label>
     {err&&<div className="loginError" role="alert"><ShieldAlert size={17}/><div><b>Sign-in failed</b><span>{err}</span></div></div>}
     <div className="loginControls"><label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span className="checkmark"><Check size={13}/></span><span>Remember me</span></label><button type="button" className="textLink" onClick={()=>{setHelp(!help);setOther(false)}}>Forgot Password?</button></div>
     {help&&<div className="loginHelper"><b>Need access?</b><span>This is a local hotel installation. Password recovery is handled by an authorized OliTechs administrator; no password is sent by this screen.</span></div>}
     <button className="primary loginSubmit" disabled={busy}>{busy?<><span className="spinner"/>Signing in…</>:<>Sign in securely <ArrowRight size={17}/></>}</button>
    </form>
    <div className="loginDivider"><span>Or</span></div>
    <button type="button" className="otherSignIn" onClick={()=>{setOther(!other);setHelp(false)}}><Layers3 size={17}/><span>Sign in with other</span><ChevronRight size={16}/></button>
    {other&&<div className="loginHelper otherHelper"><b>Alternative access</b><span>Additional sign-in providers can be enabled by your hotel administrator. Local username and password remain available.</span></div>}
    <div className="loginSignup">Don't have an account? <button type="button" onClick={()=>{window.location.href='/signup'}}>Sign Up</button></div>
    <div className="securityNote proSecurity"><LockKeyhole size={13}/><span>Your session is protected with secure local authentication.</span><span className="securityDot"/></div>
   </section>
  </div>
 </div>
}

export function App(){
 const[d,setD]=useState(null),[health,setH]=useState(null),[session,setSession]=useState(null),[page,setP]=useState(window.location.pathname==='/admin'?'admin':'dashboard'),[modal,setM]=useState(null),[toast,setT]=useState(''),[side,setSide]=useState(true),[start,setStart]=useState(new Date().toISOString().slice(0,10));
 const load=async()=>{
  try{
   const sr=await fetch(A+'/session');
   const ss=await sr.json();
   setSession(ss);
   setH(await fetch(A+'/health').then(r=>r.json()).catch(()=>({mode:'local'})));
   if(ss.authenticated){
    const br=await fetch(A+'/bootstrap');
    if(br.ok)setD(await br.json());
   }
  }catch(e){
   setSession({authenticated:false});
  }
 };
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setT(''),2500);return()=>clearTimeout(t)}},[toast]);

 if(!session)return <div className="loading">Loading secure OliTechs…</div>;
 if(!session.authenticated)return <Login onLogin={load}/>;
 const isAdmin=session.user?.role==='admin';const expired=!session.subscriptionActive;const needsCompanySetup=isAdmin&&(!session.company?.name||session.company?.name==='OliTechs Demo Hotel');
 if(expired&&!isAdmin)return <Paywall subscription={session.subscription} onLogout={async()=>{await fetch(A+'/logout',{method:'POST'});setSession({authenticated:false})}}/>;
 if(needsCompanySetup)return <CompanySetup company={session.company||{}} onDone={load}/>;
 if(!d&&page!=='admin')return <div className="loading">Loading OliTechs PMS & POS…</div>;
 const groups=[{title:'Front Office',items:[['dashboard','Dashboard',LayoutDashboard],['planner','Room Planner',CalendarDays],['reservations','Reservations',Receipt],['checkin','Check-in / Check-out',LogIn],['guests','Guests & Profiles',Users],['folios','Guest Folios',WalletCards]]},{title:'Hotel Operations',items:[['rooms','Rooms & Apartments',BedDouble],['housekeeping','Housekeeping',ClipboardCheck],['maintenance','Maintenance',Wrench],['rateplans','Rates & Availability',Tags]]},{title:'Food & Beverage',items:[['pos','Restaurant POS',Utensils],['kitchen','Kitchen / KDS',ChefHat],['menu','Menu & Products',Package]]},{title:'Management',items:[['reports','Statistics & Revenue',BarChart3],['nightaudit','Night Audit',Clock3],['users','Users & Permissions',ShieldCheck],['settings','Configuration',Settings]]}];
 if(isAdmin)groups.push({title:'Administration',items:[['admin','Admin Control Centre',ShieldAlert]]});
 const logout=async()=>{await fetch(A+'/logout',{method:'POST'});setSession({authenticated:false});setD(null)};
 return <div className="app"><header><button className="icon" onClick={()=>setSide(!side)}>{side?<X/>:<MenuIcon/>}</button><div className="brandLogoWrap"><img className="brandLogo" src="/olitechs-logo.svg" alt="OliTechs PMS & POS"/></div><div className="top"><span className="live">● {health?.mode==='postgresql-configured-json-adapter'?'PostgreSQL':'Local database'}</span>{session.subscription&&<span className={'subPill '+(session.subscriptionActive?'active':'expired')}>{session.subscription.plan} · {session.subscriptionActive?'Active':'Expired'}</span>}<button className="icon" onClick={load}><RefreshCw size={17}/></button><span className="email">{session.user?.name||'User'}</span><button className="icon" title="Lock / sign out" onClick={logout}><LockKeyhole size={17}/></button></div></header><div className="body">{side&&<aside>{groups.map(g=><div className="navGroup" key={g.title}><div className="navTitle">{g.title}</div>{g.items.map(([id,label,I])=><button className={page===id?'sel':''} key={id} onClick={()=>setP(id)}><I size={16}/><span>{label}</span></button>)}</div>)}<div className="asideBottom"><div><Database size={16}/><span>Database<br/><small>{health?.mode==='postgresql-configured-json-adapter'?'PostgreSQL server':'Local persistent DB'}</small></span></div><button onClick={async()=>{if(!isAdmin)return;await fetch(A+'/reset-demo',{method:'POST'});await load();setT('Demo data reset')}}><RefreshCw size={14}/>Reset demo data</button></div></aside>}<main>{page==='dashboard'&&<Dashboard d={d} go={setP}/>} {page==='planner'&&<Planner d={d} start={start} setStart={setStart} open={setM}/>} {page==='reservations'&&<ReservationList d={d} open={setM}/>} {page==='checkin'&&<CheckIn d={d} refresh={load} toast={setT}/>} {page==='guests'&&<Guests d={d}/>} {page==='folios'&&<Folios d={d}/>} {page==='rooms'&&<Rooms d={d} refresh={load}/>} {page==='housekeeping'&&<Housekeeping d={d} refresh={load}/>} {page==='maintenance'&&<Maintenance d={d} refresh={load}/>} {page==='rateplans'&&<RatePlans d={d}/>} {page==='pos'&&<POS d={d} refresh={load} toast={setT}/>} {page==='kitchen'&&<Kitchen d={d}/>} {page==='menu'&&<MenuPage d={d}/>} {page==='reports'&&<Reports d={d}/>} {page==='nightaudit'&&<NightAudit d={d} refresh={load} toast={setT}/>} {page==='users'&&<UsersPage d={d}/>} {page==='settings'&&<SettingsPage health={health}/>} {page==='admin'&&isAdmin&&<AdminCentre session={session} onUpdated={load} toast={setT}/>}</main></div>{modal&&<ReservationModal r={modal} d={d} close={()=>setM(null)} refresh={load} toast={setT}/>} {toast&&<div className="toast">{toast}</div>}</div>
}

function CompanySetup({company,onDone}){const[f,setF]=useState({...company,name:'',legalName:'',address:'',city:'',country:'Kenya',phone:'',email:'',website:'',currency:'KES',taxNo:'',receiptHeader:'',receiptFooter:'Thank you for choosing us.',taxLabel:'VAT',taxRate:0,invoicePrefix:'INV',receiptPrefix:'RCP',paperWidth:42});const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const save=async e=>{e.preventDefault();if(!String(f.name||'').trim()){setErr('Business / hotel name is required');return}setBusy(true);setErr('');try{const r=await fetch(A+'/admin/company',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const x=await r.json();if(!r.ok)throw Error(x.error||'Could not save company details');onDone()}catch(e){setErr(e.message)}finally{setBusy(false)}};return <div className="loginScreen"><div className="modal setupWizard"><div className="modalHead"><div><h2>Set up your company</h2><p className="muted">Enter the details that will appear on invoices, bills and thermal receipts.</p></div></div><form className="form adminForm" onSubmit={save}>{[['name','Business / hotel name'],['legalName','Legal company name'],['taxNo','Tax / PIN number'],['address','Address'],['city','City'],['country','Country'],['phone','Phone'],['email','Email'],['website','Website'],['currency','Currency'],['receiptHeader','Receipt / bill header'],['receiptFooter','Receipt / bill footer'],['taxLabel','Tax label'],['taxRate','Tax rate (%)'],['invoicePrefix','Invoice / bill prefix'],['receiptPrefix','Receipt prefix'],['paperWidth','Thermal paper width']].map(([k,l])=><label key={k}>{l}<input required={k==='name'} type={['taxRate','paperWidth'].includes(k)?'number':'text'} value={f[k]??''} onChange={e=>setF({...f,[k]:['taxRate','paperWidth'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</form>{err&&<div className="error">{err}</div>}<div className="foot"><span className="muted">You can change these details later in Administration.</span><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save company & continue'}</button></div></div></div>}
function Paywall({subscription,onLogout}){return <div className="loginScreen"><div className="loginCard paywall"><div className="shield warning"><ShieldAlert size={38}/></div><h1>Subscription required</h1><p>The hotel subscription is not currently active.</p><div className="subscriptionBox"><b>{subscription?.plan||'Plan'}</b><span>Status: {subscription?.status||'expired'}</span><span>Expiry: {subscription?.expiresAt?new Date(subscription.expiresAt).toLocaleString('en-GB'):'Not set'}</span></div><p className="muted">Please contact your OliTechs administrator to renew the hotel subscription.</p><button onClick={onLogout}>Sign out</button></div></div>}

function AdminCentre({session,onUpdated,toast}){
 const[c,setC]=useState(session.company||{}),[sub,setSub]=useState(session.subscription||{}),[tab,setTab]=useState('overview'),[app,setApp]=useState(session.companyApplication||{}),[printers,setPrinters]=useState([]),[msg,setMsg]=useState('');
 const loadAdmin=async()=>{try{const [a,p]=await Promise.all([fetch(A+'/admin/company-application'),fetch(A+'/admin/printers')]);if(a.ok)setApp(await a.json());if(p.ok)setPrinters(await p.json())}catch(e){}};useEffect(()=>{loadAdmin()},[]);
 const saveCompany=async()=>{const r=await fetch(A+'/admin/company',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(c)});const x=await r.json();if(r.ok){setC(x);setMsg('Company details saved to this local machine');toast('Company details saved');onUpdated()}else setMsg(x.error||'Unable to save')};
 const review=async(status)=>{const r=await fetch(A+'/admin/company-application',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({status,company:c,notes:app.notes||''})});const x=await r.json();if(r.ok){setApp(x);toast(`Company registration ${status}`);onUpdated()}else setMsg(x.error||'Unable to update registration')};
 const saveSub=async()=>{const r=await fetch(A+'/admin/subscription',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(sub)});const x=await r.json();if(r.ok){setSub(x);toast('Subscription updated');onUpdated()}else setMsg(x.error||'Unable to save')};
 const addPrinter=async()=>{const pr={name:'New Thermal Printer',type:'network',ip:'',port:9100,printerName:'',department:'reception',documents:['order','bill','receipt'],enabled:true};const r=await fetch(A+'/admin/printers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(pr)});if(r.ok){setPrinters([...printers,await r.json()]);toast('Printer added')}};
 const updatePrinter=async(pr)=>{const r=await fetch(A+'/admin/printers/'+pr.id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(pr)});if(r.ok){const saved=await r.json();setPrinters(printers.map(x=>x.id===pr.id?saved:x));toast('Printer saved')}};
 const samplePrint=async(type)=>{const pr=printers.find(x=>(x.documents||[]).includes(type)&&x.enabled!==false)||printers[0];if(!pr)return toast('Configure a thermal printer first');const r=await fetch(A+'/admin/print-document',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({printerId:pr.id,documentType:type,reference:'SAMPLE-001',customer:c.name||'Guest',items:[{name:type==='bill'?'Accommodation / Services':'Thermal printer test',qty:1,price:100}],subtotal:100,tax:100*(Number(c.taxRate||0)/100),total:100+(100*(Number(c.taxRate||0)/100)),paymentMethod:'Sample'})});const x=await r.json();toast(r.ok?type.toUpperCase()+' sample printed':x.error||'Print failed')};
 const testPrinter=async(pr)=>{const r=await fetch(A+'/admin/printers/'+pr.id+'/test',{method:'POST'});const x=await r.json();toast(r.ok?'Test print sent':x.error||'Test print failed')};
 const removePrinter=async(pr)=>{if(!confirm(`Remove ${pr.name}?`))return;await fetch(A+'/admin/printers/'+pr.id,{method:'DELETE'});setPrinters(printers.filter(x=>x.id!==pr.id));toast('Printer removed')};
 const pending=app.status==='pending'||app.status==='submitted'; const activeSub=sub.status==='active'&&(!sub.expiresAt||new Date(sub.expiresAt)>new Date());
 return <section><Head title="Administrator Dashboard" sub="Protected platform administration, company approval, subscriptions and printing"><span className="adminShield"><ShieldCheck size={16}/> Administrator only</span></Head>
 <div className="adminTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Activity size={16}/>Overview</button><button className={tab==='registration'?'active':''} onClick={()=>setTab('registration')}><Building2 size={16}/>Company registration</button><button className={tab==='printers'?'active':''} onClick={()=>setTab('printers')}><Printer size={16}/>Thermal printers</button><button className={tab==='subscription'?'active':''} onClick={()=>setTab('subscription')}><CreditCard size={16}/>Subscription & Paywall</button></div>
 {tab==='overview'&&<><div className="adminStats"><div className="adminMetric"><Activity/><b>{app.status||'pending'}</b><span>Registration status</span></div><div className="adminMetric"><CreditCard/><b>{sub.plan||'Trial'}</b><span>{activeSub?'Subscription active':'Subscription blocked'}</span></div><div className="adminMetric"><Printer/><b>{printers.length}</b><span>Configured printers</span></div><div className="adminMetric"><ShieldCheck/><b>{dStatus(app.status)}</b><span>System access</span></div></div><div className="dashboardGrid"><div className="panel"><h2>Administrator actions</h2><Action label="Review company registration" icon={Building2} onClick={()=>setTab('registration')}/><Action label="Configure thermal printers" icon={Printer} onClick={()=>setTab('printers')}/><Action label="Manage subscription and paywall" icon={CreditCard} onClick={()=>setTab('subscription')}/></div><div className="panel"><h2>Security</h2><p className="muted">The administrator area is protected separately from normal hotel operations. Approval is required before non-admin hotel users can operate the installation.</p><div className="subscriptionBox"><span>Company access: <b>{app.status==='approved'?'Approved':'Awaiting approval'}</b></span><span>Subscription: <b>{activeSub?'Active':'Blocked'}</b></span></div></div></div></>}
 {tab==='registration'&&<div className="panel adminPanel"><h2>Company registration and approval</h2><p className="muted">Register the hotel on this local machine, review the submitted details, and explicitly approve or reject access to OliTechs.</p><div className="registrationStatus"><span className={'statusDot '+(app.status==='approved'?'ok':pending?'pending':'blocked')}></span><b>{String(app.status||'pending').toUpperCase()}</b><span>{app.reviewedAt?`Reviewed ${new Date(app.reviewedAt).toLocaleString('en-GB')}`:'Awaiting administrator review'}</span></div><div className="form adminForm">{[['name','Trading / hotel name'],['legalName','Legal company name'],['registrationNo','Company registration number'],['taxNo','Tax / PIN number'],['address','Address'],['city','City'],['country','Country'],['phone','Phone'],['email','Email'],['website','Website'],['currency','Currency'],['timezone','Timezone'],['receiptHeader','Receipt / bill header'],['receiptFooter','Receipt / bill footer'],['taxLabel','Tax label'],['taxRate','Tax rate (%)'],['invoicePrefix','Invoice / bill prefix'],['receiptPrefix','Receipt prefix'],['paperWidth','Thermal paper width (characters)']].map(([k,l])=><label key={k}>{l}<input type={['taxRate','paperWidth'].includes(k)?'number':'text'} value={c[k]??''} onChange={e=>setC({...c,[k]:['taxRate','paperWidth'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}</div><label className="full adminNote">Administrator review notes<textarea value={app.notes||''} onChange={e=>setApp({...app,notes:e.target.value})}/></label><div className="foot"><span>{msg}</span><button onClick={saveCompany}><Save size={15}/>Save locally</button><button className="danger" onClick={()=>review('rejected')}>Reject</button><button className="primary" onClick={()=>review('approved')}><CheckCircle2 size={15}/>Approve company</button></div></div>}
 {tab==='printers'&&<div><div className="printerIntro panel"><div><h2>Thermal printer configuration</h2><p className="muted">Route orders, bills and receipts to reception, kitchen, bar or another outlet. Network printers can print directly by IP and port. Bluetooth and USB/wired printers use the Windows printer queue.</p></div><button className="primary" onClick={addPrinter}><Plus size={15}/>Add printer</button></div><div className="printerGrid">{printers.map(pr=><PrinterCard key={pr.id} pr={pr} update={updatePrinter} test={testPrinter} remove={removePrinter}/>)}</div>{!printers.length&&<div className="empty">No thermal printers configured.</div>}<div className="panel printSamples"><h2>Branded receipt & bill preview</h2><p className="muted">The saved company details are automatically placed in the header/footer of thermal receipts and bills.</p><div className="printerActions"><button onClick={()=>samplePrint('receipt')}><ReceiptText size={14}/>Print sample receipt</button><button onClick={()=>samplePrint('bill')}><FileText size={14}/>Print sample bill</button></div></div></div>}
 {tab==='subscription'&&<div className="panel adminPanel"><h2>Subscription & Paywall</h2><p className="muted">Monitor the hotel subscription from the administrator dashboard. Expired, suspended or past-due subscriptions block normal hotel users while keeping administrator access available.</p><div className="subscriptionBox"><b>{sub.plan||'Plan'}</b><span>Status: {sub.status||'active'}</span><span>Expires: {sub.expiresAt?new Date(sub.expiresAt).toLocaleString('en-GB'):'not configured'}</span><span>Room limit: {sub.maxRooms||'Unlimited'}</span><span>{sub.expiresAt&&new Date(sub.expiresAt)>new Date()?Math.ceil((new Date(sub.expiresAt)-new Date())/864e5)+' days remaining':'Subscription expired'}</span></div><div className="form adminForm">{[['plan','Plan name'],['status','Status'],['startsAt','Start date/time'],['expiresAt','Expiry date/time'],['maxRooms','Maximum rooms']].map(([k,l])=><label key={k}>{l}{k==='status'?<select value={sub[k]||'active'} onChange={e=>setSub({...sub,[k]:e.target.value})}><option value="active">Active</option><option value="past_due">Past due</option><option value="expired">Expired</option><option value="suspended">Suspended</option></select>:<input type={k==='maxRooms'?'number':k.endsWith('At')?'datetime-local':'text'} value={k.endsWith('At')&&sub[k]?String(sub[k]).slice(0,16):sub[k]||''} onChange={e=>setSub({...sub,[k]:k==='maxRooms'?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="foot"><span/><button className="primary" onClick={saveSub}><Save size={15}/>Save subscription</button></div></div>}
 </section>}

function dStatus(status){return status==='approved'?'Enabled':status==='pending'||status==='submitted'?'Pending':'Blocked'}

function PrinterCard({pr,update,test,remove}){const[local,setLocal]=useState(pr);useEffect(()=>setLocal(pr),[pr]);const set=(k,v)=>setLocal({...local,[k]:v});return <div className="panel printerCard"><div className="printerHead"><div><Printer/><h3>{pr.name||'Thermal printer'}</h3><small>{pr.department||'reception'} · {pr.type||'network'}</small></div><label className="switch"><input type="checkbox" checked={local.enabled!==false} onChange={e=>set('enabled',e.target.checked)}/><span>Enabled</span></label></div><div className="printerForm"><label>Printer name<input value={local.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Connection<select value={local.type||'network'} onChange={e=>set('type',e.target.value)}><option value="network">Network / IP</option><option value="bluetooth">Bluetooth</option><option value="usb">USB / Wired</option></select></label><label>Outlet / destination<select value={local.department||'reception'} onChange={e=>set('department',e.target.value)}><option value="reception">Reception</option><option value="kitchen">Kitchen</option><option value="bar">Bar</option><option value="restaurant">Restaurant</option><option value="other">Other</option></select></label>{pr.type==='network'?<><label>IP address<input placeholder="192.168.1.100" value={local.ip||''} onChange={e=>set('ip',e.target.value)}/></label><label>Port<input type="number" value={local.port||9100} onChange={e=>set('port',Number(e.target.value))}/></label></>:<label>Windows printer name<input placeholder="Exact Windows printer queue name" value={local.printerName||''} onChange={e=>set('printerName',e.target.value)}/></label>}<label className="full">Print documents<select multiple value={local.documents||[]} onChange={e=>set('documents',[...e.target.selectedOptions].map(x=>x.value))}><option value="order">Orders</option><option value="bill">Bills</option><option value="receipt">Receipts</option></select></label></div><div className="printerActions"><button onClick={()=>test(local)}><ReceiptText size={14}/>Test print</button><button className="primary" onClick={()=>update(local)}><Save size={14}/>Save</button><button className="danger" onClick={()=>remove(pr)}><Trash2 size={14}/>Remove</button></div></div>}

export default App;
